/**
 * Назначение: локальный entrypoint для запуска self-hosted HTTP runtime и печати основных UI/API endpoint-ов.
 */
import { createSaasApp } from './backend/app'
import { resolveSaasAppConfig } from './backend/config'

const config = resolveSaasAppConfig()
const app = createSaasApp(config)

app.listen(config.port, () => {
    console.log(`AQA Pulse API started on http://127.0.0.1:${config.port}`)
    console.log(`React dashboard UI: http://127.0.0.1:${config.port}/`)
    console.log(`React static shell: http://127.0.0.1:${config.port}/static/index.html`)
    console.log(`Frontend assets: http://127.0.0.1:${config.port}/ui-assets/`)
    console.log(`Storage driver: ${config.storageDriver}`)
    console.log(`SQLite path: ${config.sqlitePath ?? 'not configured'}`)
    console.log(`Workspace data root: ${config.dataRoot}`)
    console.log(`UI dist path: ${config.distPath}`)
    console.log(`Archive path: ${config.archiveRootPath}`)
    console.log(`Admin token: ${config.adminToken ? 'configured' : 'not configured (admin routes are open locally)'}`)
    console.log(`Dev bootstrap: ${config.allowDevBootstrap ? 'enabled' : 'disabled'}`)
    console.log(`Workspace auth: ${config.requireWorkspaceAuth ? 'required' : 'optional'}`)
    console.log('Available UI endpoints:')
    console.log('  GET /')
    console.log('  GET /static/index.html')
    console.log('  GET /ui-assets/*')
    console.log('  GET /api/health')
    console.log('  GET /api/summary')
    console.log('  GET /api/runs')
    console.log('  GET /api/run/:id')
    console.log('  GET /api/flaky')
    console.log('  GET /api/errors/clusters')
    console.log('  GET /api/metrics/cost')
    console.log('  GET /test/:name')
    console.log('  GET /api/test/:name')
    console.log('Available SaaS foundation endpoints:')
    console.log('  POST /api/dev/bootstrap')
    console.log('  GET /api/workspaces')
    console.log('  GET /api/workspaces/:slug')
    console.log('  POST /api/workspaces')
    console.log('  POST /api/workspaces/:slug/api-keys')
    console.log('  POST /api/workspaces/:slug/users')
    console.log('  POST /api/workspaces/:slug/ingestions')
    console.log('  GET /api/workspaces/:slug/summary')
    console.log('  GET /api/workspaces/:slug/runs')
    console.log('  GET /api/workspaces/:slug/run/:id')
    console.log('  GET /api/workspaces/:slug/flaky')
    console.log('  GET /api/workspaces/:slug/errors/clusters')
    console.log('  GET /api/workspaces/:slug/metrics/cost')
    console.log('  GET /api/workspaces/:slug/test/:name')
    console.log('  GET /w/:slug')
    console.log('  GET /w/:slug/test/:name')
})
