export { ApiStore, type ApiFilters, type TestHistoryConflict, type TestHistoryResponse } from '../api-store'
export {
    buildAdvancedMetrics,
    buildAdvancedMetricsFromArchivedRuns,
    buildDashboardSummary,
    formatDate,
    formatDuration,
    formatPercent,
    loadReporterReport,
    readDashboardSummary,
    type DashboardAdvancedMetrics,
    type DashboardAvailableFilters,
    type DashboardFilters,
    type DashboardKpis,
    type DashboardRunMetadata,
    type PrecomputedCodeQualityFileFacts,
    type PrecomputedCodeQualitySourceFacts,
    type PrecomputedCodeQualityTestFacts,
    type DashboardSummary,
    type ReporterAttempt,
    type ReporterRoot,
    type ReporterTest,
    normalizePrecomputedSourceFacts,
    writeJsonFile,
    writeTextFile,
} from '../dashboard-utils'
export {
    appendHistoryEntry,
    archiveHistoryRun,
    buildHistoryEntryId,
    readDashboardHistory,
    type ArchivedRunMetadata,
    type ArchivedRunRecord,
    type DashboardHistory,
    type DashboardHistoryEntry,
    writeDashboardHistory,
} from '../history-utils'
export { createAdminApp, createRuntimeApp, createSaasApp } from './app'
export * as applicationAdmin from './application/admin'
export * as applicationRuntime from './application/runtime'
export {
    buildAdminIngestionHealthReport,
    bootstrapWorkspaceForDev,
    createWorkspaceApiKeyCommand,
    createWorkspaceCommand,
    createWorkspaceShareLinkCommand,
    createWorkspaceUserCommand,
    deleteWorkspaceApiKeyCommand,
    deleteWorkspaceCommand,
    deleteWorkspaceUserCommand,
    disableWorkspaceApiKeyCommand,
    disableWorkspaceUserCommand,
    ensureWorkspaceReadModelInitialized,
    loginViaWorkspaceShareLinkToken,
    loginAdmin,
    loginWorkspaceApiKey,
    loginWorkspaceUser,
    logoutAdmin,
    logoutWorkspaceReadSession,
    openWorkspaceShareLink,
    queryDashboardCostMetricsPayload,
    queryDashboardErrorClustersPayload,
    queryDashboardFlakyPayload,
    queryDashboardRunById,
    queryDashboardRuns,
    queryDashboardSummary,
    queryTestHistoryForApi,
    queryTestHistoryForShell,
    readAdminBootstrapSessionState,
    readWorkspaceBootstrapSessionState,
    revokeWorkspaceSessionCommand,
    updateServerSettingsCommand,
    updateWorkspaceCommand,
    updateWorkspaceUserRoleCommand,
    type AdminActorContext,
    type AdminAuthRegistryPort,
    type AdminWorkspaceCommandRuntime,
    type AdminWorkspaceRegistryPort,
    type AuthSessionConfig,
    type AdminLoginResult,
    type WorkspaceApiKeyLoginResult,
    type WorkspaceShareLinkAuthConfig,
    type WorkspaceShareLinkOpenResult,
    type WorkspaceShareLinkRegistryPort,
    type WorkspaceShareLinkTokenLoginResult,
    type WorkspaceUserLoginResult,
} from './application'
export { normalizeShareLinkTtlMinutes } from './domain/share-link-rules'
export {
    buildFrontendServiceUrls,
    buildWorkspaceShareLinkUrl,
    ensureDevBootstrapEnabled,
    getFiltersFromRequest,
    getRouteParam,
    normalizeIngestionPayload,
    normalizePaginationQueryValue,
    pickOptionalString,
    pickQueryParam,
    readCookieValue,
    readAdminBootstrapSession,
    readWorkspaceBootstrapSession,
    registerAdminRoutes,
    registerCommonHttpErrorHandlers,
    registerRuntimeRoutes,
    sendArtifactFile,
    sendUnknownWorkspaceShareLinkErrorHtml,
    sendWorkspaceShareLinkErrorShell,
    type AdminRoutesContext,
    type RuntimeRoutesContext,
} from './infrastructure/http'
export * as persistence from './infrastructure/persistence'
export * as security from './infrastructure/security'
export { applyServerSettingsToConfig, buildServerSettingsDefaults } from './infrastructure/server-settings'
export {
    createAdminGuard,
    createWorkspaceApiKeyGuard,
    createWorkspaceResolver,
    createWorkspaceUserGuard,
    extractAccessToken,
    getWorkspaceAuthFromLocals,
    getWorkspaceFromLocals,
    getWorkspaceUserAuthFromLocals,
    requireWorkspaceFromLocals,
} from './auth'
export { resolveSaasAppConfig, type SaasAppConfig } from './config'
export * as domain from './domain'
export { ingestReporterRun } from './run-ingestion.service'
export * as infrastructure from './infrastructure'
export { uploadReportToWorkspace, type UploadReportOptions } from './upload-report'
export {
    createBackendStorage,
    FileSystemBackendStorage,
    FileSystemDashboardReadStorage,
    FileSystemWorkspaceRegistryStorage,
    FileSystemWorkspaceRunStorage,
    SqliteBackendStorage,
    SqliteWorkspaceRegistryStorage,
    SqliteWorkspaceRunStorage,
    type BackendStorage,
    type DashboardReadStorage,
    type DashboardStoragePaths,
    type WorkspaceRegistryStorage,
    type WorkspaceRunStorage,
} from './storage'
export { WorkspaceRegistry } from './workspace-registry'
export {
    getDevDataRoot,
    getWorkspacePaths,
    getWorkspacePathsFromDataRoot,
    getWorkspaceRegistryPath,
    getWorkspaceRegistryPathFromDataRoot,
    resolveWorkspaceDataRoot,
} from './workspace-paths'
export type {
    CreateWorkspaceInput,
    CreateWorkspaceUserInput,
    IngestionRequestPayload,
    IngestionResult,
    StorageDriver,
    WorkspaceApiAuthResult,
    WorkspaceDescriptor,
    WorkspacePaths,
    WorkspaceProvisioningResult,
    WorkspaceRecord,
    WorkspaceRegistrySnapshot,
    WorkspaceUserAuthResult,
    WorkspaceUserProvisioningResult,
    WorkspaceUserRole,
    WorkspaceUserRecord,
} from './contracts'

